spring:
   mvc:
      view:
         prefix: WEB-INF/jsp/
         suffix: .jsp
         
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/shmarket?characterEncoding=utf-8
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver
      
   http:
      encoding:
         force: true
         charset: UTF-8
         enabled: true
         
   resources:
      # web文件映射（数组）
      staticLocations:
         - classpath:/static
         - file:/d:/blog/
   
   
   # 邮件服务配置
   mail:
      #邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 864849403@qq.com
      # 发送密码
      password: uasvgffqwtkybdah
      # 默认字符集编码
      default-encoding: UTF-8

# 邮件发送地址
mail:
   fromMail:
      addr: 864849403@qq.com

# 更改端口
server:
   port: 80
   tomcat:
      uri-encoding: UTF-8

# 日志输出
logging:
   level:
      com:
         example: trace